service: laravel-serverless

provider:
  name: aws
  region: ap-south-1
  memorySize: 1024
  timeout: 30

  ecr:
    images:
      laravel:
        uri: 960631463638.dkr.ecr.ap-south-1.amazonaws.com/lambda-compatible-image1:latest

functions:
  laravel:
    image:
      name: laravel
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY


  artisan:
    handler: artisan
    runtime: provided.al2
    layers:
      - ${bref:layer.php-83}       # CLI runtime (not fpm!)
      - ${bref:layer.console}      # Needed to run Artisan commands


resources:
  Resources: {}
