service: laravel-serverless

provider:
  name: aws
  region: ap-south-1
  memorySize: 1024
  timeout: 30

  ecr:
    images:
      laravel:
        uri: 136003615631.dkr.ecr.ap-south-1.amazonaws.com/lambda-compatible-image1:latest

functions:
  # Main Laravel web handler
  laravel:
    image:
      name: laravel
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

  # Artisan command runner (uses same image)
  artisan:
    image:
      name: laravel
      command: ["php", "artisan"]
    timeout: 900
    memorySize: 1024
