service: laravel-serverless

plugins:
  - ./vendor/bref/bref

provider:
  name: aws
  region: ap-south-1
  memorySize: 1024
  timeout: 30

  ecr:
    images:
      lambda-fpm:
        uri: 136003615631.dkr.ecr.ap-south-1.amazonaws.com/lambda-fpm:latest

  environment:
    APP_NAME: Serverless-App
    APP_ENV: production
    APP_KEY: ${env:APP_KEY}
    APP_DEBUG: false

    DB_CONNECTION: mysql
    DB_HOST: ${env:DB_HOST}
    DB_PORT: 3306
    DB_DATABASE: laravel_db
    DB_USERNAME: admin
    DB_PASSWORD: ${env:DB_PASSWORD}

    QUEUE_CONNECTION: sqs
    SQS_QUEUE: laravel-queue
    SQS_PREFIX: https://sqs.ap-south-1.amazonaws.com/136003615631
    SEEDER_SECRET: ${env:SEEDER_SECRET}
    AWS_BUCKET: ${env:AWS_BUCKET}

functions:
  # Main Laravel web handler
  laravel:
    image:
      name: lambda-fpm
    timeout: 29
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

  # Queue worker - Fixed runtime and added Bref layer
  queueProcessor:
    handler: Bref\LaravelBridge\Queue\QueueHandler
    runtime: provided.al2
    layers:
      - ${bref:layer.php-83}
    timeout: 900
    memorySize: 1024
    events:
      - sqs:
          arn: arn:aws:sqs:ap-south-1:136003615631:laravel-queue

  # Scheduled tasks - Fixed runtime and added Bref layer
  # scheduler:
  #   handler: Bref\LaravelBridge\Main\ScheduleHandler
  #   runtime: provided.al2
  #   layers:
  #     - ${bref:layer.php-83}
  #   timeout: 120
  #   memorySize: 1024
  #   events:
  #     - schedule: rate(5 minutes)
