service: laravel-serverless

provider:
  name: aws
  region: ap-south-1
  memorySize: 1024
  timeout: 30

  ecr:
    images:
      laravel:
        uri: 136003615631.dkr.ecr.ap-south-1.amazonaws.com/lambda-compatible-image1:latest

  environment:
    APP_NAME: Serverless-App
    APP_ENV: local
    APP_KEY: ${env:APP_KEY}
    APP_DEBUG: true

    DB_CONNECTION: mysql
    DB_HOST: laravel-db.cx4eimm4y97f.ap-south-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_DATABASE: laravel_db
    DB_USERNAME: admin
    DB_PASSWORD: ${env:DB_PASSWORD}

    QUEUE_CONNECTION: sqs
    SQS_QUEUE: laravel-queue
    SQS_PREFIX: https://sqs.ap-south-1.amazonaws.com/136003615631

functions:
  # Main Laravel web handler
  laravel:
    image:
      name: laravel
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

  # Artisan command runner (uses same image)
  artisan:
    image:
      name: laravel
      command: ["php", "artisan"]
    timeout: 900
    memorySize: 1024

  queueWorker:
    image:
      name: laravel
      command: ["php", "artisan", "queue:work", "sqs", "--once", "--tries=3", "--timeout=900"]
    timeout: 900
    memorySize: 1024
    events:
      - sqs:
          arn: arn:aws:sqs:ap-south-1:136003615631:laravel-queue
