version: "3.8"

services:
  laravel-php:
    build:
      context: ../..
      dockerfile: ./deploy/ecs/Dockerfile   # <-- unified Dockerfile (with supervisord)
    container_name: laravel-php
    ports:
      - "8080:80"

    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: true
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
